/**
 * InputSource
 * Date: Sep 12, 2005 12:51:10 PM
 * <p/>
 * (c) 2005 IceCube Collaboration
 */

package icecube.daq.testUtil;

import java.nio.channels.SelectableChannel;
import java.io.IOException;

/**
 * This interface provides the input channels to the component to be tested
 *
 * @author artur
 * @version $Id: InputSource.java,v 1.3 2005/10/20 00:27:31 artur Exp $
 */
public interface InputSource {

    /**
     * return an array of SelectableChannel(s) generated by this object
     *
     * @return an array of SelectableChannel
     */
    public SelectableChannel getSourceChannel();

    /**
     * start processing data by reading them from the source and feeding the other end of the pipe
     *
     * @throws IOException
     */
    public void startProcessing() throws IOException;

    /**
     * check to see if the input source is running
     * @return
     */
    public boolean isRunning();

    /**
     * stop processing data
     *
     * @throws IOException
     */
    public void stopProcessing() throws IOException;

    /**
     * set the rate
     * @param rate
     */
    public void setRate(double rate);

    /**
     * get the rate for this input source
     * @return rate
     */
    public double getRate();

    /**
     * set the num of doms
     * @param numDoms
     */
    public void setNumDoms(int numDoms);

    /**
     * get the num of doms for this input source
     * @return numDoms
     */
    public int getNumDoms();

    /**
     * set source ID
     * @param sourceID
     */
    public void setSourceID(int sourceID);

    /**
     * get the sourceID for this input source
     * @return sourceID
     */
    public int getSourceID();

    /**
     * set the trigger mode
     * @param triggerMode
     */
    public void setTriggerMode(int triggerMode);

    /**
     * get the trigger mode for this input source
     * @return triggerMode
     */
    public int getTriggerMode();

    /**
     * set payloadType
     * @param payloadType
     */
    public void setPayloadType(String payloadType);

    /**
     * get payloadType for this input source
     * @return payloadType
     */
    public String getPayloadType();

    /**
     * set the duration of the process in minutes
     * @param minutes
     */
    public void setProcessDuration(int minutes);

    /**
     * get the duration of the process in minutes
     * @return an int value
     */
    public int getProcessDuration();

    /**
     * Set number of hits
     * @param hits
     */
    public void setNumOfHits(long hits);

    /**
     * get the number of hits
     * @return a long value
     */
    public long getNumOfHits();
}
